export const locatorEmp = {
    employee_profile: "//a[@class='nav-link nav-dropdown-toggle'][text()='Employee Profile']",
    employee_profile_maintenance: "//a[contains(@class,'nav-dropdown-toggle')  and (normalize-space()='Employee Profile Maintenance'  or normalize-space()='ปรับปรุงข้อมูลพนักงาน')]", 
    employee_movement: "//a[@href='/persadmin/employeemovement'][normalize-space()='Employee Movement']", 
    new_movement_button: "//button[@class='btn btn-md btn-primary'][normalize-space()='New Movement' or normalize-space()='สร้าง Movement']",
    movementType : "//ng-select[@id='eventTypeCode']",
    movementReason : "//ng-select[@id='eventReasonCode']",
    empTitle : "//ng-select[@id='newEmpTitle']",
    empFirstName : "//input[@formcontrolname='newEmpFirstName']",
    empLastName : "//input[@formcontrolname='newEmpLastName']",
    submitButton: "//button[@type='submit']",
    ddlemployee: "(//input[@role='combobox'])[2]",
    yesButton: "//button[@id='yesButton']",
    empCodegen :"//input[@formcontrolname='newEmpCode']",
    empCompany: "//ng-select[@id='comCode']",
    empOrgCode: "//ng-select[@id='orgCode']",
    empPosCode: "//ng-select[@id='posCode']",
    empFTE: "//input[@formcontrolname='FTE']",
    empjobLevel: "//ng-select[@id='jobLevel']",
    payrollAreaCode: "//ng-select[@id='payrollAreaCode']",
    empGroupCode: "//ng-select[@id='empGroupCode']",
    empSubGroupCode: "//ng-select[@id='empSubGroupCode']",
    persAreaCode: "//ng-select[@id='persAreaCode']",
    persSubAreaCode: "//ng-select[@id='persSubAreaCode']",
    costCenter: "//ng-select[@id='costCenter']",
    empFirstNameEn: "//input[@formcontrolname='secondFName']",
    empLastNameEn: "//input[@formcontrolname='secondLName']",
    maritalCode : "//ng-select[@id='maritalCode']",
    birthDate : "//input[@formcontrolname='birthDate']",
    religionCode : "//ng-select[@id='religionCode']",
    attachTypeCode: "//ng-select[@id='attachTypeCode']",
    fileName: "//input[@id='fileName']",
    identityNumber: "//input[@formcontrolname='identityNumber']",
    province: "//ng-select[@id='province']",
    district: "//ng-select[@id='district']",
    subDistrict: "//ng-select[@id='subDistrict']",
    email: "//input[@formcontrolname='commuInfo']",
    countryCode: "//ng-select[@formcontrolname='countryCode']",
    genderCode: "//ng-select[@formcontrolname='genderCode']",
    titleSelected: "//ng-select[@formcontrolname='titleSelected']",
    firstFName: "//input[@formcontrolname='firstFName']",
    firstLName: "//input[@formcontrolname='firstLName']",
    secondFName: "//input[@formcontrolname='secondFName']",
    secondLName: "//input[@formcontrolname='secondLName']",
    bankKeyCode: "//ng-select[@formcontrolname='bankKeyCode']",
    accountNumber: "//input[@formcontrolname='accountNumber']",
    amount: "//input[@formcontrolname='amount']",
}; 