name: Playwright CI

on:
  push:
    branches: [main]

jobs:
  Run_Script:
    name: Run_Script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Run Playwright Tests
        run: npx playwright test
        env:
          CI: true

      - name: Upload raw report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/

  Report:
    name: Report
    needs: Run_Script
    runs-on: ubuntu-latest

    steps:
      - name: Download report
        uses: actions/download-artifact@v4
        with:
          name: playwright-report
          path: playwright-report

      - name: Generate Report Summary
        run: |

          REPORT=playwright-report/results.json
          PASSED=$(jq '.stats.expected' $REPORT)
          FAILED=$(jq '.stats.unexpected' $REPORT)
          SKIPPED=$(jq '.stats.skipped' $REPORT)
          TOTAL=$((PASSED + FAILED + SKIPPED))

          echo "## 🧪 Test Report Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Status | Value |" >> $GITHUB_STEP_SUMMARY
          echo "|--------|-------|" >> $GITHUB_STEP_SUMMARY
          echo "| ✅ Passed | $PASSED |" >> $GITHUB_STEP_SUMMARY
          echo "| ❌ Failed | $FAILED |" >> $GITHUB_STEP_SUMMARY
          echo "| ⏭ Skipped | $SKIPPED |" >> $GITHUB_STEP_SUMMARY
          echo "| 📊 Total | $TOTAL |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

  Send_Mail:
    name: Send_Mail
    needs: Report
    runs-on: ubuntu-latest

    steps:
      - name: Send email notification
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true

          username: ${{ secrets.USERNAME_MAIL}}
          password: ${{ secrets.PASSWORD_MAIL }}

          subject: "Playwright Test Result - ${{ job.status }}"
          to: sutat.up@pinno.io
          cc: sutat_1604@hotmail.com, bigkk2008@hotmail.com
          from: Playwright CI <${{ secrets.USERNAME_MAIL }}>

          body: |
            Playwright CI Finished 🚀

            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Status: ${{ job.status }}


            View report:
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
